// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use placeholder URL for generation - actual connection happens at runtime
    url: process.env.DATABASE_URL || "postgresql://user:password@localhost:5432/dbname",
  },
});
